import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Nav from '../components/nav'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CS630 Data Structures and Algorithms Textbook</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav active="Home" />
      <main className={styles.main}>
        <div className={styles.banner}>
          <h1 className={styles.title}>
            Data Structures and Algorithms Textbook
          </h1>

          <p className={styles.description}>
            Learn the basics of algorithms with this accessibly-written textbook!
            {/* {' '} */}
            {/* <code className={styles.code}>pages/index.js</code> */}
          </p>
        </div>
        <div className={styles.grid}>
          <Link href="/writing">
            <a className={styles.card}>
            <h1>Get started! &rarr;</h1>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.andover.edu"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by CSC630 Phillips Academy. 
          {/* {' '} */}
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  )
}
